- name: install zip
  become: true
  command: sudo apt install zip -y

- name: install awscli
  become: true
  command: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  command: unzip awscliv2.zip
  command: sudo ./aws/install
  command: aws --version
