- name: Run updates  
  hosts: all
  become: true
  tasks:
  - name: updating packages
    command: sudo apt-get update -y

- name: Setup Jenkins server
  hosts: jenkins
  become: true

  vars:
    jenkins_plugins:
      - git
      - pipeline
      - pipeline-github-lib
      - pipeline-stage-view
      - github-branch-source

  roles:
    - jenkins # Install git so it can call the repo, and Java which jenkins depends on.
    - geerlingguy.jenkins # Install Jenkins
    - kubectl # Install kubectl (based on aws instructions at https://docs.aws.amazon.com/eks/latest/userguide/install-kubectl.html)
    - apprequirements # Install requirements to run tests on the app
  tasks:
  - name: configuring jenkins user
    command: sudo usermod -aG sudo jenkins

